### ISSUE TITLE
Data previews not showing

### ISSUE THREAD

**Issue by zelima** [datahq/specstore#12]
Config passed to planner is missing `derived/preview`, so planner is never returning preview resource

## Acceptance criteria

* [ ] we have previews 

## Tasks

* [ ] add `derived/preview` as aditional allowed type
* [ ] update tests

**Comment by zelima** [comment]
FIXED

**Comment by rufuspollock** [comment]
@zelima can you clarify what the config is and how that relates to what the planner generates. Is the config the "spec" or something else? Shouldn't it be the planner that generates the derived/preview?

**Comment by zelima** [comment]
@rufuspollock yes, the planner should generate derived resources, but according to configurations passed from FlowManager. Configurations, in this case, are `allowed_types`  https://github.com/datahq/specstore/blob/65080cc6885fa0c21595657fc88bf07cb2c1faea/flowmanager/controllers.py#L12
