### ISSUE TITLE
State of pipelines is not correct

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/specstore#4]
From https://github.com/datahq/specstore/blob/b4bbf554869230fdc2664a41524dc834f331dd2e/specstore/controllers.py#L77-L78 we can see that `state` set to `REGISTERED` when update time of pipeline is older than update time of spec. So I have tested with one package to see what happens when I just repush my dataset without any changes:

Checked source api to see the state of the pipeline https://api.datahub.io/source/90998f7f90e086bd5fc7c9075dfda43b/co2-ppm/info and in here `update_time` of `pipeline` is the first push time:
```
{
  ...
  "pipeline": {
    "pipeline": [...],
    "update_time": "2017-08-15T05:54:36.488076"
  },
  ...
}
```

But if we take a look at `specs` table in the database, we can see that `updated_at` value is the date of the last push (`2017-08-29`). So because of that we are always getting TRUE in the following statement:

```python
if spec.updated_at and spec.updated_at.isoformat() > update_time:
    resp['state'] = 'REGISTERED'
```

Possible solution: pipeline's `update_time` should be updated as the spec's one.

**Comment by akariv** [comment]
I believe this problem was solved in https://github.com/frictionlessdata/datapackage-pipelines-sourcespec-registry/commit/c233cf35baf2f48fb3800df766705da723e4ecf3

Please re-open if this reoccurs.
