### ISSUE TITLE
Change polling to push notification in pipelines

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/specstore#5]
Problem: currently there is delay in starting a pipeline as pipeline system polls for new things to do rather than running on push.

Solution: switch to push.

* new API for pipelines system
* connect to source spec registry ...

**Comment by zelima** [comment]
@anuveyatsu is this still actual

**Comment by anuveyatsu** [comment]
@zelima I don't think so - haven't noticed any sort of delays after a new system was deployed. So closing this issue now.
