### ISSUE TITLE
Add information about how to specify schedule in README

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/specstore#9]
I wanted to check how should I specify a schedule in source spec but couldn't find any information in the README. Would be useful in the future to have it there.

**Comment by zelima** [comment]
This was closed accidentally

**Comment by zelima** [comment]
FIXED in https://github.com/datahq/specstore/commit/694a15959b585eeac7ee82026b677a7c1e109a11 and https://github.com/datahq/planner/commit/d4dbc6bbd4d215ed1617969e3a502953b6b62910
